// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dwwfvgcorxepkhkizaby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3d2Z2Z2NvcnhlcGtoa2l6YWJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMDQyODEsImV4cCI6MjA2OTc4MDI4MX0.Z8B7MM7BbD5FjlTsSGTj2qPX5SOSoM6AEasBo2FXsik";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});